export const INSTANCE_REPOSITORY = 'INSTANCE_REPOSITORY';
export const STEP_REPOSITORY = 'STEP_REPOSITORY';
export const ORG_CHART_REPOSITORY = 'ORG_CHART_REPOSITORY';
export const SLA_SCHEDULER = 'SLA_SCHEDULER';
